def count_bases(s):
	a=0
	t=0
	c=0
	g=0

	for i in range(0,len(s)):
		if(s[i]=='A'):
			a+=1
		elif(s[i]=='G'):
			g+=1
		elif(s[i]=='C'):
			c+=1
		elif(s[i]=='T'):
			t+=1

	ret=""
	ret += str(a)+" "+str(c)+" "+str(g)+" "+str(t)
	return ret

s="AACAATTTAGGATCATATACTATGACTAGTACTCATGCATTGCAGTAGATGCTTGCCGGTAACTATAGCCGTAAACTTGAAGGACGGTCAATAGTTAACCAGACGGTGAGAAGGATCGGATATTCTACCCGCTCATTTGCGCCATTGATCCGGGTATCTCCCATATGTCAGAGAGGCCCTAAGGTATCGGACATTAGGCGGAAAACCCCCGTTCGGTCCTTGCTAGCGTAAATCTGTACGCCCTGGATTTCCCACCTTCTCTAACGTAAGGTACGAGATCGACGGAATACGAGGCTTAGCTGCTTCTACAGCAGACTCGTCCGGGATAAATGCTACGGCTGGCACCGCTGCCCCAGGTAAAATAGTCGCCATCGAAGCAGCTTTGAGTCCTCTAGCCTTCCCATGGAGTCAAGGCTCTCCCCGACCCTCTTGTGTCTCCACATATGACGCCGGGGCTCGCAGACATCCTTTATGAACTTTTAGCTGTTCCTCGGTGTTCTTTTTTTTAAGCAGAACCCCACCAGTTGGGAAGAGATCGTTTGCCGCGGTCTTATGTTTACGAAGTCTACGTGGTTGCTAGGCTAATGTATTAATTCGCACGTAGAACACCACTCGACGCGTTTGCCAGCAAGCGTAGTTGCTACCATGCGCTTTACGGTGTTTGTATAAGGAAAGGTGGTCATTCTTGGGTCCAGCGCGCTAACCGGCGAGAAACGCCACGTAGTACCCCGTTAAGAGGTAGGTGTACAACAGTCGTGCACTTCTCTGCGGACAAATTTCCATAGTCGGATGGGAACTCTGGAGTAGTGGACAGGTCCGATTGTCCCAAATGCTTACAGGATGAGCGAAGTCGGAAGCGCATTGATCGAGACAGTGTGATGAGTCACCAAACGATGCGCTCCGCGAGTAGGTAGCCGAGCGCGTTGCGAATGACCAAAAGGGCCCACGTCGCCATTCGCTCATAAACATCACGCCGGAGAACTACTTG"
sol=""
sol=count_bases(s)
print(sol)


