def complement_bases(m):
	ret=""

	for i in range(0,len(m)):
		if(m[i]=='A'):
			ret+=str('T')
		elif(m[i]=='T'):
			ret+=str('A')
		elif(m[i]=='C'):
			ret+=str('G')
		elif(m[i]=='G'):
			ret+=str('C')

	return ret

s="CCCGGGTCGTCACCAGATTGCTCTTCTTGGTGCATATGAGCGGTTTTCCCAACCGGCTGAAAGGAGTAATTGAGGCATGCTGGCCAGCGGCACCGCTTGGATGTATTCTTTTAGTGGTCGTCATCGATGGCTCCTACTAACCGGTCAATAACCAATAATCGCCTACCGAAAGCCGCCCAGCGAGCATATGTCCATGCCACGTGATACATGAGGACTTTCAGCCTCCTAAGCTATGATGCGTCTGATTTTTTCCAACCTGATTGAATTTTGATGTTTTTGCTCCTCTGCTGACTATGGCTGTCCACTCAAAACGAAGCTCCAACCTTCGCCACATTTGCCCATGATTCCTGCCCCTACCATCAAGTACACGTATGTTACAACCCTCAAAAGAGCTAAACAGGCGACCCATGGCTCTAGTTCACAGAGTAGGATCCGTCGGCAGTGGGGGGGGATTCGGGCGCTCCTATCTCGCCAAGTTAATCCATCCTGGAATCATCCGAGGGTCACACGGTATTCTTCCTGAAGCTGAAAGTTGAACCCTTCACAAGACTAGGAGCTAGTACGGCTGCGATAGACTGGGCAAACGTCGCTGATTCAGAGTAGACGGTCTGCAAAGGAGGTATTAAAAGCCATGATAATATCGAACCGTATAGCGTGCCGACATCCACAGGCTTTCTAACGACCACGGCTGCATAAGAAAATGTGCAGGCGGCACTAAACATGCAAAATATCTCTCAAAAGTCAGCCGTATGCGGTATTAGGTTTCCGGGCCAACCTGCCATTGAGGACTTCTGGCCCAGGAATCTTAGGATCAGACCACGA"
l=[]
for i in range(0,len(s)):
	l.append(s[i])

print(l)
l.reverse()
print(l)
m=""

for i in range(0,len(s)):
	m = m+str(l[i])

print(m)

complement=complement_bases(m)
print("------------------------------")
print(complement)
